apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: filter
spec:
  template:
    spec:
      containers:
      - image:  villardl/filter-nodejs
        env:
        - name: FILTER
          value: event.data.assigned